### ISSUE TITLE
プログレスバーの仮組み

### ISSUE THREAD

**Issue by 618knot** [618knot/circle_judge#32]
#30 

親　：ProgressDotsBar
子供：ProgressDot

**Comment by ItisNoMatter** [comment]
[containerで形をいじる方法](https://www.choge-blog.com/programming/flutter%E3%80%8C%E5%86%86%E3%80%8D%E3%82%92%E6%8F%8F%E7%94%BB%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95/)
