### ISSUE TITLE
問題の読み込み中にローディングの表示をする

### ISSUE THREAD

**Issue by Naja-Naja** [618knot/circle_judge#42]
読み込み時間が長いため、スタートボタンを押してから画像が表示されるまでの間にローディングのアニメーションか何かを表示する処理を実装する（未確定仕様

**Comment by yud0uhu** [comment]
ローディングアニメーション参考
titlePageのGAME_ID_INIT()呼び出し時に嚙ませてみる？
https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html
