### ISSUE TITLE
app_barにグラデーションつける

### ISSUE THREAD

**Issue by ItisNoMatter** [618knot/circle_judge#87]
gradient_app_bar
[参考](https://qiita.com/azukisiromochi/items/bedf81bae8f0470c58a3)

**Comment by yud0uhu** [comment]
@ItisNoMatter これなんですが、https://github.com/618knot/circle_judge/pull/86 をやっていたら副産的にできたので、こちらで回収してしまって大丈夫ですかね？

**Comment by ItisNoMatter** [comment]
@yud0uhu 
ありがたすぎます
